name: Build entservices-apis on Ubuntu

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  ThunderComponents:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential git

      - name: Clone ThunderTools
        run: git clone -b R4_4 https://github.com/rdkcentral/ThunderTools.git

      - name: Clone Thunder
        run: git clone -b R4_4 https://github.com/rdkcentral/Thunder.git

      - name: Install jsonref
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install jsonref

      - name: Apply ThunderTools Patch
        run: |
          cd ThunderTools
          git apply $GITHUB_WORKSPACE/.github/Patches/00010-R4.4-Add-support-for-project-dir.patch
          cd ..

      - name: Apply Thunder Patch
        run: |
          cd Thunder
          git apply $GITHUB_WORKSPACE/.github/Patches/1004-Add-support-for-project-dir.patch
          cd ..

      - name: Build ThunderTools
        run: |
          cmake -G Ninja -S ThunderTools -B ThunderTools/build -DCMAKE_INSTALL_PREFIX="install"
          cmake --build ThunderTools/build --target install

      - name: Build Thunder
        run: |
          cmake -G Ninja -S Thunder -B Thunder/build \
            -DBINDING="127.0.0.1" \
            -DCMAKE_BUILD_TYPE="Debug" \
            -DCMAKE_INSTALL_PREFIX="install" \
            -DPORT="55555" \
            -DTOOLS_SYSROOT="${PWD}" \
            -DINITV_SCRIPT=OFF
          cmake --build Thunder/build --target install

      - name: Build entservices-apis
        run: |
          cmake -G Ninja -S . -B build \
            -DCMAKE_INSTALL_PREFIX="install" \
            -DTOOLS_SYSROOT="${PWD}"
          cmake --build build --target install
